
server:
  port: 8081
spring:
  application:
    name: restaurantservice
  datasource:
    url: jdbc:mysql://localhost:3307/food_ordering
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
